# Generated by Django 2.1.1 on 2018-12-17 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boogle', '0002_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(default='', max_length=30)),
                ('title', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=30)),
                ('price', models.IntegerField()),
                ('link', models.CharField(default='', max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('articleAuthor', models.CharField(default='', max_length=30, null=True)),
                ('bookStatus', models.CharField(default='', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boogle.Article')),
                ('commentAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='imageLink',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='marketPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='publishedYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='interestedBooks',
            field=models.ManyToManyField(related_name='notificationRecipients', to='boogle.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boogle.Book'),
        ),
    ]
